/**
 * Favicons for managed processes: found by asking the running service itself, kept on disk so an
 * application card still carries its icons after everything in it has stopped.
 *
 * Discovery is what a browser does, cut down: fetch the page at `/`, take the icon its `<link>` tags
 * declare, and fall back to `/favicon.ico`. Only ports a scan has already tied to a managed process
 * are ever probed, and only on loopback — this module never talks to a service the user did not
 * configure, and never follows a page off this machine.
 *
 * The image type comes from the bytes, never from the response header. A single-page dev server
 * answers `/favicon.ico` with its HTML shell and a 200, so a header would call that page an icon.
 *
 * The cache is disposable — a missing, torn or unreadable entry just means the next run of that
 * process finds its icon again — so entries are written plainly and read tolerantly rather than
 * given the atomic, fsynced treatment configuration gets.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { FAVICON_DIR } from './config.js';

const PROBE_TIMEOUT_MS = 5_000;
const MAX_PAGE_BYTES = 524_288;
const MAX_ICON_BYTES = 102_400;

/** A process listening on more ports than this is not going to have its icon on the fourth. */
const MAX_PORTS_PROBED = 3;
const MAX_DECLARED_ICONS = 4;
const MAX_REDIRECTS = 3;

/**
 * A dev server can hold its port for a while before it will answer (Next compiles `/` on first
 * request), so one run of a process gets a few attempts, spaced out, before discovery gives up on it
 * until the next start.
 */
const MAX_ATTEMPTS_PER_RUN = 3;
const RETRY_AFTER_MS = 30_000;

/** Ids are generated by applications.js; anything else never becomes a file name. */
const SAFE_ID = /^[A-Za-z0-9_-]+$/;

const LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '[::1]']);

const CONTENT_TYPES = new Set(['image/png', 'image/x-icon', 'image/gif', 'image/jpeg', 'image/webp', 'image/svg+xml']);

const bytesOf = (...values) => Buffer.from(values);

/** Magic numbers, checked in order. SVG has none, so it is recognised from its text below. */
const SIGNATURES = [
  { type: 'image/png', offset: 0, bytes: bytesOf(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a) },
  { type: 'image/x-icon', offset: 0, bytes: bytesOf(0x00, 0x00, 0x01, 0x00) },
  { type: 'image/gif', offset: 0, bytes: Buffer.from('GIF8') },
  { type: 'image/jpeg', offset: 0, bytes: bytesOf(0xff, 0xd8, 0xff) },
  { type: 'image/webp', offset: 8, bytes: Buffer.from('WEBP') },
];

/** An XML declaration, comments and a doctype may all come before the root element. */
const SVG_ROOT = /^﻿?\s*(?:<\?xml[^>]*>\s*)?(?:<!--[\s\S]*?-->\s*)*(?:<!DOCTYPE svg[^>]*>\s*)?<svg[\s>]/i;

const LINK_TAG = /<link\b[^>]*>/gi;
const ATTRIBUTE = /([\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))/g;

/**
 * Cached icons by process id, loaded once at startup.
 * @type {Map<string, {processId: string, applicationId: string, sourceUrl: string,
 *                     contentType: string, fetchedAt: string, data: string}>}
 */
const icons = new Map();

/**
 * Discovery bookkeeping for the current run of each process. Memory only: a restarted manager has
 * no runs to resume, and every process it starts is a fresh run anyway.
 * @type {Map<string, {startedAt: string, attempts: number, lastAttemptAt: number,
 *                     inFlight: boolean, found: boolean}>}
 */
const runs = new Map();

const isSafeId = (value) => typeof value === 'string' && SAFE_ID.test(value);

const cacheFile = (processId) => path.join(FAVICON_DIR, `${processId}.json`);

/** @param {Buffer} bytes @returns {string|null} */
function sniff(bytes) {
  const signature = SIGNATURES.find(
    ({ offset, bytes: magic }) => bytes.subarray(offset, offset + magic.length).equals(magic)
  );
  if (signature) return signature.type;
  return SVG_ROOT.test(bytes.subarray(0, 4_096).toString('utf8')) ? 'image/svg+xml' : null;
}

/**
 * The only URLs discovery will fetch: a page on this machine, or an icon inlined into one. Anything
 * else is a service reaching out on the manager's behalf, which is not what showing an icon is for.
 */
function isAllowedUrl(url) {
  if (url.protocol === 'data:') return true;
  return url.protocol === 'http:' && (LOOPBACK_HOSTS.has(url.hostname) || url.hostname.startsWith('127.'));
}

/** Stops reading the moment the body outgrows what it could legitimately be. */
async function readBounded(body, maxBytes) {
  if (!body) return Buffer.alloc(0);
  const chunks = [];
  let size = 0;
  for await (const chunk of body) {
    size += chunk.length;
    if (size > maxBytes) return null;
    chunks.push(chunk);
  }
  return Buffer.concat(chunks);
}

/**
 * GET a loopback URL. Redirects are followed by hand so every hop can be checked: `redirect:
 * 'follow'` would let a page on this machine send the request somewhere that is not.
 * @returns {Promise<{url: string, contentType: string, bytes: Buffer}|null>} null for any failure
 */
async function fetchLocal(href, maxBytes) {
  const signal = AbortSignal.timeout(PROBE_TIMEOUT_MS);
  let url = new URL(href);
  try {
    for (let hop = 0; hop <= MAX_REDIRECTS && isAllowedUrl(url); hop += 1) {
      const res = await fetch(url, { redirect: 'manual', signal });
      const location = res.headers.get('location');
      if (res.status >= 300 && res.status < 400 && location) {
        await res.body?.cancel();
        url = new URL(location, url);
        continue;
      }
      if (!res.ok) {
        await res.body?.cancel();
        return null;
      }
      const bytes = await readBounded(res.body, maxBytes);
      return bytes && { url: url.href, contentType: res.headers.get('content-type') ?? '', bytes };
    }
  } catch {
    // Refused, reset, timed out, not HTTP at all (a database on the port) — all mean "no icon here".
  }
  return null;
}

/** `rel` is a token list: "shortcut icon" is an icon, "mask-icon" is a monochrome Safari pin. */
function iconRank(rel) {
  const tokens = rel.toLowerCase().split(/\s+/);
  if (tokens.includes('icon')) return 0;
  if (tokens.includes('apple-touch-icon')) return 1;
  return null;
}

/** Each attribute's value is in whichever of the three quoting groups matched. */
const attributesOf = (tag) =>
  Object.fromEntries(
    [...tag.matchAll(ATTRIBUTE)].map(([, name, ...values]) => [
      name.toLowerCase(),
      values.find((value) => value !== undefined),
    ])
  );

/**
 * The icons a page declares, best first. `Array.prototype.sort` is stable, so within a rank they keep
 * document order. A regex over the tags rather than a parser: only `<link>` attributes are needed,
 * and a page whose markup defeats this simply falls through to `/favicon.ico`.
 */
function declaredIcons(html, pageUrl) {
  const found = [];
  for (const [tag] of html.matchAll(LINK_TAG)) {
    const { rel, href } = attributesOf(tag);
    const rank = rel && href ? iconRank(rel) : null;
    if (rank === null) continue;
    try {
      found.push({ rank, url: new URL(href.replaceAll('&amp;', '&'), pageUrl) });
    } catch {
      // An href that is not a URL at all is one icon fewer, not a failed discovery.
    }
  }
  return found
    .sort((a, b) => a.rank - b.rank)
    .slice(0, MAX_DECLARED_ICONS)
    .map((candidate) => candidate.url);
}

/** A data: URL is the page's own markup, and storing it as the "source" would store the icon twice. */
const sourceOf = (url, pageUrl) => (url.protocol === 'data:' ? `${pageUrl} (inline)` : url.href);

async function fetchIcon(url, pageUrl) {
  const res = await fetchLocal(url.href, MAX_ICON_BYTES);
  const contentType = res && res.bytes.length > 0 ? sniff(res.bytes) : null;
  return contentType ? { sourceUrl: sourceOf(url, pageUrl), contentType, bytes: res.bytes } : null;
}

/** @param {string} origin e.g. `http://127.0.0.1:5173` */
async function iconAt(origin) {
  const page = await fetchLocal(`${origin}/`, MAX_PAGE_BYTES);
  const html = page?.contentType.includes('html') ? page.bytes.toString('utf8') : '';
  const pageUrl = page?.url ?? `${origin}/`;
  const candidates = [...declaredIcons(html, pageUrl), new URL('/favicon.ico', origin)];
  for (const url of candidates) {
    const icon = await fetchIcon(url, pageUrl);
    if (icon) return icon;
  }
  return null;
}

/**
 * Where to reach a listener from this machine. One listener is merged across address families, so
 * it can hold several binds; IPv4 is preferred because it is what a dual-stack server answers on
 * too. A wildcard bind is reachable on loopback. A bind to one LAN address is not, and probing it
 * would mean leaving loopback, so a listener with nothing else is skipped.
 * @param {{port: number, addresses: string[]}} listener
 */
function originOf({ port, addresses }) {
  if (addresses.some((address) => address === '0.0.0.0' || address.startsWith('127.'))) {
    return `http://127.0.0.1:${port}`;
  }
  if (addresses.some((address) => address === '::' || address === '::1')) return `http://[::1]:${port}`;
  return null;
}

async function findIcon(listeners) {
  const origins = [...new Set(listeners.map(originOf).filter(Boolean))].slice(0, MAX_PORTS_PROBED);
  for (const origin of origins) {
    const icon = await iconAt(origin);
    if (icon) return icon;
  }
  return null;
}

/**
 * A new run of a process always gets a first attempt — its icon may have changed since the cached
 * one was taken. Within a run, a failed attempt earns a retry later, and a found icon ends it.
 */
function isDue({ processId, startedAt }) {
  const run = runs.get(processId);
  if (!run || run.startedAt !== startedAt) return true;
  if (run.inFlight || run.found || run.attempts >= MAX_ATTEMPTS_PER_RUN) return false;
  return Date.now() - run.lastAttemptAt >= RETRY_AFTER_MS;
}

function beginAttempt({ processId, startedAt }) {
  const previous = runs.get(processId);
  const attempts = previous?.startedAt === startedAt ? previous.attempts + 1 : 1;
  runs.set(processId, { startedAt, attempts, lastAttemptAt: Date.now(), inFlight: true, found: false });
}

function endAttempt({ processId, startedAt }, found) {
  const run = runs.get(processId);
  // Forgotten, or restarted, while the probe was out: the bookkeeping belongs to someone else now.
  if (run?.startedAt === startedAt) runs.set(processId, { ...run, inFlight: false, found });
}

/**
 * @returns {Promise<boolean>} whether the cache changed. Finding the icon that is already cached
 *   is not a change — every restart would otherwise refetch every open dashboard's list.
 */
async function store({ processId, applicationId }, icon) {
  const data = icon.bytes.toString('base64');
  const current = icons.get(processId);
  if (current?.data === data && current.sourceUrl === icon.sourceUrl) return false;
  const entry = {
    processId,
    applicationId,
    sourceUrl: icon.sourceUrl,
    contentType: icon.contentType,
    fetchedAt: new Date().toISOString(),
    data,
  };
  icons.set(processId, entry);
  // The icon is already live in memory; a disk that refuses it only costs a rediscovery next time.
  await fs.mkdir(FAVICON_DIR, { recursive: true });
  await fs.writeFile(cacheFile(processId), JSON.stringify(entry), { mode: 0o600 }).catch((err) => {
    console.error(`[paddock] favicon for ${processId} not cached: ${err.message}`);
  });
  return true;
}

async function discoverOne(target) {
  beginAttempt(target);
  let icon = null;
  try {
    icon = await findIcon(target.listeners);
  } finally {
    endAttempt(target, Boolean(icon));
  }
  // Removed from the configuration while the probe was out: storing now would resurrect it.
  if (!icon || !runs.has(target.processId)) return false;
  return store(target, icon);
}

const isEntry = (value) =>
  isSafeId(value?.processId) &&
  typeof value.applicationId === 'string' &&
  typeof value.sourceUrl === 'string' &&
  CONTENT_TYPES.has(value.contentType) &&
  typeof value.fetchedAt === 'string' &&
  typeof value.data === 'string';

async function readEntry(name) {
  try {
    const entry = JSON.parse(await fs.readFile(path.join(FAVICON_DIR, name), 'utf8'));
    return isEntry(entry) && `${entry.processId}.json` === name ? entry : null;
  } catch {
    return null; // torn or hand-edited: the next run of that process finds its icon again
  }
}

/** Load what earlier runs of the manager found. A missing directory is an empty cache. */
export async function load() {
  const names = await fs.readdir(FAVICON_DIR).catch(() => []);
  const entries = await Promise.all(names.filter((name) => name.endsWith('.json')).map(readEntry));
  for (const entry of entries) if (entry) icons.set(entry.processId, entry);
}

/**
 * Probe every target that is due, concurrently across processes and one port at a time within one.
 * @param {{applicationId: string, processId: string, startedAt: string|null,
 *          listeners: {port: number, addresses: string[]}[]}[]} targets running managed processes and
 *   the listeners a scan tied to them
 * @returns {Promise<boolean>} whether any cached icon changed
 */
export async function discover(targets) {
  const due = targets.filter((target) => isSafeId(target.processId) && target.startedAt && isDue(target));
  const changed = await Promise.all(due.map(discoverOne));
  return changed.some(Boolean);
}

/**
 * What a view model carries: where the icon came from and when. Never the bytes — the application
 * list is refetched on every status change and read by agents, neither of which wants base64 in it.
 * @param {string} processId
 * @returns {{sourceUrl: string, fetchedAt: string}|null}
 */
export function describe(processId) {
  const entry = icons.get(processId);
  return entry ? { sourceUrl: entry.sourceUrl, fetchedAt: entry.fetchedAt } : null;
}

/**
 * Every cached icon as a data URL, which an `<img>` renders without the dashboard ever serving the
 * bytes itself: an SVG served from the manager's own origin could run script there if opened in a
 * tab, while one inside a data URL in an `<img>` cannot.
 * @param {Set<string>} processIds the processes that still exist
 * @returns {Record<string, {applicationId: string, sourceUrl: string, fetchedAt: string, dataUrl: string}>}
 */
export function list(processIds) {
  const listed = [...icons.values()]
    .filter((entry) => processIds.has(entry.processId))
    .map((entry) => [
      entry.processId,
      {
        applicationId: entry.applicationId,
        sourceUrl: entry.sourceUrl,
        fetchedAt: entry.fetchedAt,
        dataUrl: `data:${entry.contentType};base64,${entry.data}`,
      },
    ]);
  return Object.fromEntries(listed);
}

/**
 * A removed process takes its icon with it. Synchronous in effect, like the rest of runtime
 * discard: the memory is dropped now, and a file that will not delete is only an unused cache entry.
 * @param {string} processId
 */
export function forget(processId) {
  icons.delete(processId);
  runs.delete(processId);
  if (!isSafeId(processId)) return;
  fs.rm(cacheFile(processId), { force: true }).catch(() => {});
}
