/**
 * Log capture: a bounded in-memory ring buffer per process, plus an append-only JSONL file.
 *
 * The ring exists for cursor stability rather than speed — every entry carries a seq drawn from
 * one global counter, so a UI or an agent can poll with `sinceSeq` over a single process or a
 * whole application, and an eviction never renumbers anything a caller is still holding.
 * Disk writes go through jsonl-sink.js, one sink per process, so a failing disk disables
 * persistence for that process instead of taking the manager down with it.
 */
import path from 'node:path';
import { appendLine, closeSink, createSink, tailLines } from './jsonl-sink.js';
import { LOG_DIR, LOG_BUFFER_LINES, LOG_FILE_MAX_BYTES, LOG_PERSIST } from './config.js';

/**
 * @typedef {{seq:number, ts:string, stream:'stdout'|'stderr', processId:string,
 *            message:string}} LogEntry
 */

const DEFAULT_LIMIT = 500;
const MAX_LIMIT = 10_000;

/** Ids are generated by applications.js; anything else never reaches the filesystem. */
const SAFE_ID = /^[A-Za-z0-9_-]+$/;

/**
 * Built here instead of pasted: a CSI/OSC pattern copied from memory matched the empty string at
 * every position and stripped nothing at all. Every alternative below consumes at least two chars.
 */
const ANSI = new RegExp(
  [
    '[\\u001b\\u009b][[][0-?]*[ -/]*[@-~]', // CSI — colours, cursor movement, erase
    '\\u001b[\\]][^\\u0007\\u001b]*(?:\\u0007|\\u001b\\\\)', // OSC — window titles, hyperlinks
    '\\u001b[@-Z\\\\-_]', // two-character escapes
  ].join('|'),
  'g'
);

const sanitize = (message) => String(message).replace(ANSI, '').replace(/\r+$/, '');

/** Anything not literally 'stderr' is stdout, so a stray value can never hide from a filter. */
const streamOf = (stream) => (stream === 'stderr' ? 'stderr' : 'stdout');

/**
 * @type {Map<string, {applicationId:string, processId:string,
 *                     entries:Array<LogEntry|undefined>, writes:number}>}
 */
const buffers = new Map();

/** @type {Map<string, import('./jsonl-sink.js').Sink>} */
const sinks = new Map();

/** One counter for every process, so one cursor is valid for a process and for an application. */
let nextSeq = 1;

const bufferKey = (applicationId, processId) => `${applicationId}\u0000${processId}`;

const isSafeId = (value) => typeof value === 'string' && SAFE_ID.test(value);

const logFile = (applicationId, processId) =>
  isSafeId(applicationId) && isSafeId(processId)
    ? path.join(LOG_DIR, applicationId, `${processId}.jsonl`)
    : null;

/**
 * Append a line for one process.
 * @param {string} applicationId
 * @param {string} processId
 * @param {'stdout'|'stderr'} stream
 * @param {string} message raw line, still carrying ANSI escapes and a possible trailing CR
 * @returns {LogEntry} the stored entry, with its seq
 */
export function append(applicationId, processId, stream, message) {
  const buffer = bufferFor(applicationId, processId);
  const entry = {
    seq: nextSeq++,
    ts: new Date().toISOString(),
    stream: streamOf(stream),
    processId,
    message: sanitize(message),
  };
  store(buffer, entry);
  persist(applicationId, processId, entry);
  return entry;
}

/**
 * Read buffered entries for one process or for several merged, always ascending by seq.
 * @param {{applicationId:string, processIds:string[], limit?:number, sinceSeq?:number,
 *          stream?:'stdout'|'stderr', order?:'asc'}} q `order` is accepted only as 'asc' — the
 *   cursor protocol has no meaning in any other order, so entries are always ascending.
 * @returns {{entries: LogEntry[], nextSeq: number, dropped: boolean}}
 */
export function read(q) {
  const processIds = Array.isArray(q.processIds) ? q.processIds : [];
  const selected = processIds.map((processId) => bufferFor(q.applicationId, processId));
  const cursor = toCursor(q.sinceSeq);
  const limit = Math.min(Math.max(Math.trunc(Number(q.limit)) || DEFAULT_LIMIT, 1), MAX_LIMIT);

  const matched = [];
  let dropped = false;
  for (const buffer of selected) {
    const entries = ascending(buffer);
    // Only a real cursor can be stale: a caller that sent none has missed nothing by definition.
    if (cursor !== null && evicted(buffer) && entries[0].seq > cursor) dropped = true;
    for (const entry of entries) {
      if (q.stream && entry.stream !== q.stream) continue;
      if (cursor !== null && entry.seq < cursor) continue;
      matched.push(entry);
    }
  }
  matched.sort((a, b) => a.seq - b.seq);

  return { entries: matched.slice(-limit), nextSeq, dropped };
}

/**
 * Drop everything buffered for a process. The seq counter keeps climbing so cursors held elsewhere
 * stay meaningful, and the JSONL file is left alone — clearing a view is not deleting history.
 * The emptied buffer is kept rather than deleted: dropping it would let the next read rehydrate the
 * very history that was just cleared. Its write stream is closed, since the only caller is a config
 * deletion and the process will never write again.
 * @param {string} applicationId
 * @param {string} processId
 */
export function clear(applicationId, processId) {
  const key = bufferKey(applicationId, processId);
  const buffer = buffers.get(key);
  if (buffer) {
    buffer.entries.fill(undefined);
    buffer.writes = 0;
  }
  const sink = sinks.get(key);
  if (sink) closeSink(sink);
}

/** Flush and close every JSONL stream. Queued appends are written first. */
export async function closeAll() {
  await Promise.all([...sinks.values()].map(closeSink));
}

/**
 * A cursor is either a real number or nothing: `Number('')` is 0, so an absent or blank `sinceSeq`
 * read as a number would look like the cursor of a client that had already seen the whole log and
 * would raise a spurious `dropped` on every fresh reader.
 */
const toCursor = (value) => {
  if (typeof value === 'string' && value.trim() === '') return null;
  if (value === null || value === undefined) return null;
  const seq = Number(value);
  return Number.isFinite(seq) ? seq : null;
};

function bufferFor(applicationId, processId) {
  const key = bufferKey(applicationId, processId);
  const existing = buffers.get(key);
  if (existing) return existing;

  const capacity = Math.max(1, Math.trunc(LOG_BUFFER_LINES));
  const buffer = { applicationId, processId, entries: new Array(capacity), writes: 0 };
  buffers.set(key, buffer);
  // First touch after a manager restart: the ring is empty, but the JSONL still holds the history.
  rehydrate(buffer);
  return buffer;
}

const evicted = (buffer) => buffer.writes > buffer.entries.length;

const store = (buffer, entry) => {
  buffer.entries[buffer.writes % buffer.entries.length] = entry;
  buffer.writes += 1;
};

/** The ring in seq order: the oldest live slot first, wrapping at the write head. */
function ascending(buffer) {
  const { entries, writes } = buffer;
  if (!evicted(buffer)) return entries.slice(0, writes);
  const head = writes % entries.length;
  return entries.slice(head).concat(entries.slice(0, head));
}

// ---------------------------------------------------------------------------------------------
// Cold-start rehydration — reads the tail of the JSONL once, when a buffer is first created.
// ---------------------------------------------------------------------------------------------

function rehydrate(buffer) {
  if (!LOG_PERSIST) return;
  const file = logFile(buffer.applicationId, buffer.processId);
  if (!file) return;
  for (const line of tailLines(file, buffer.entries.length)) {
    const entry = parseStored(line, buffer.processId);
    if (entry) store(buffer, entry);
  }
}

/** Old lines are renumbered: seq is a live cursor, and the previous run's numbering is gone. */
function parseStored(line, processId) {
  try {
    const { ts, stream, message } = JSON.parse(line);
    if (typeof message !== 'string') return null;
    return { seq: nextSeq++, ts: String(ts), stream: streamOf(stream), processId, message };
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------------------------
// JSONL persistence — one sink per process, created on first write.
// ---------------------------------------------------------------------------------------------

function persist(applicationId, processId, entry) {
  if (!LOG_PERSIST) return;
  const sink = sinkFor(applicationId, processId);
  if (!sink) return;
  const { seq, ts, stream, message } = entry;
  appendLine(sink, `${JSON.stringify({ seq, ts, stream, message })}\n`);
}

function sinkFor(applicationId, processId) {
  const key = bufferKey(applicationId, processId);
  const existing = sinks.get(key);
  if (existing) return existing;
  const file = logFile(applicationId, processId);
  if (!file) return null;
  const sink = createSink(file, LOG_FILE_MAX_BYTES);
  sinks.set(key, sink);
  return sink;
}
