/**
 * Log capture: a bounded in-memory ring buffer per process, plus an append-only JSONL file.
 *
 * The ring exists for cursor stability rather than speed — every entry carries a seq drawn from
 * one global counter, so a UI or an agent can poll with `sinceSeq` over a single process or a
 * whole application, and an eviction never renumbers anything a caller is still holding.
 * Disk writes go through one queue per process so an append, a rotation and the shutdown flush can
 * never interleave, and a failing disk disables persistence for that process instead of taking the
 * manager down with it.
 */
import fs from 'node:fs';
import { mkdir, rename, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import { once } from 'node:events';
import { LOG_DIR, LOG_BUFFER_LINES, LOG_FILE_MAX_BYTES, LOG_PERSIST } from './config.js';

/**
 * @typedef {{seq:number, ts:string, stream:'stdout'|'stderr', processId:string,
 *            message:string}} LogEntry
 */

const DEFAULT_LIMIT = 500;
const MAX_LIMIT = 10_000;
const TAIL_CHUNK_BYTES = 65_536;
const TAIL_MAX_SCAN_BYTES = 262_144;

/** Ids are generated by applications.js; anything else never reaches the filesystem. */
const SAFE_ID = /^[A-Za-z0-9_-]+$/;

/**
 * Built here instead of pasted: a CSI/OSC pattern copied from memory matched the empty string at
 * every position and stripped nothing at all. Every alternative below consumes at least two chars.
 */
const ANSI = new RegExp(
  [
    '[\\u001b\\u009b][[][0-?]*[ -/]*[@-~]', // CSI — colours, cursor movement, erase
    '\\u001b[\\]][^\\u0007\\u001b]*(?:\\u0007|\\u001b\\\\)', // OSC — window titles, hyperlinks
    '\\u001b[@-Z\\\\-_]', // two-character escapes
  ].join('|'),
  'g'
);

const noop = () => {};

const sanitize = (message) => String(message).replace(ANSI, '').replace(/\r+$/, '');

/** Anything not literally 'stderr' is stdout, so a stray value can never hide from a filter. */
const streamOf = (stream) => (stream === 'stderr' ? 'stderr' : 'stdout');

/**
 * @type {Map<string, {applicationId:string, processId:string,
 *                     entries:Array<LogEntry|undefined>, writes:number}>}
 */
const buffers = new Map();

/**
 * @type {Map<string, {file:string, stream:fs.WriteStream|null, bytes:number,
 *                     queue:Promise<void>, disabled:boolean}>}
 */
const sinks = new Map();

/** One counter for every process, so one cursor is valid for a process and for an application. */
let nextSeq = 1;

const bufferKey = (applicationId, processId) => `${applicationId}\u0000${processId}`;

const isSafeId = (value) => typeof value === 'string' && SAFE_ID.test(value);

const logFile = (applicationId, processId) =>
  isSafeId(applicationId) && isSafeId(processId)
    ? path.join(LOG_DIR, applicationId, `${processId}.jsonl`)
    : null;

/**
 * Append a line for one process.
 * @param {string} applicationId
 * @param {string} processId
 * @param {'stdout'|'stderr'} stream
 * @param {string} message raw line, still carrying ANSI escapes and a possible trailing CR
 * @returns {LogEntry} the stored entry, with its seq
 */
export function append(applicationId, processId, stream, message) {
  const buffer = bufferFor(applicationId, processId);
  const entry = {
    seq: nextSeq++,
    ts: new Date().toISOString(),
    stream: streamOf(stream),
    processId,
    message: sanitize(message),
  };
  store(buffer, entry);
  persist(applicationId, processId, entry);
  return entry;
}

/**
 * Read buffered entries for one process or for several merged, always ascending by seq.
 * @param {{applicationId:string, processIds:string[], limit?:number, sinceSeq?:number,
 *          stream?:'stdout'|'stderr', order?:'asc'}} q `order` is accepted only as 'asc' — the
 *   cursor protocol has no meaning in any other order, so entries are always ascending.
 * @returns {{entries: LogEntry[], nextSeq: number, dropped: boolean}}
 */
export function read(q) {
  const processIds = Array.isArray(q.processIds) ? q.processIds : [];
  const selected = processIds.map((processId) => bufferFor(q.applicationId, processId));
  const cursor = toCursor(q.sinceSeq);
  const limit = Math.min(Math.max(Math.trunc(Number(q.limit)) || DEFAULT_LIMIT, 1), MAX_LIMIT);

  const matched = [];
  let dropped = false;
  for (const buffer of selected) {
    const entries = ascending(buffer);
    // Only a real cursor can be stale: a caller that sent none has missed nothing by definition.
    if (cursor !== null && evicted(buffer) && entries[0].seq > cursor) dropped = true;
    for (const entry of entries) {
      if (q.stream && entry.stream !== q.stream) continue;
      if (cursor !== null && entry.seq < cursor) continue;
      matched.push(entry);
    }
  }
  matched.sort((a, b) => a.seq - b.seq);

  return { entries: matched.slice(-limit), nextSeq, dropped };
}

/**
 * Drop everything buffered for a process. The seq counter keeps climbing so cursors held elsewhere
 * stay meaningful, and the JSONL file is left alone — clearing a view is not deleting history.
 * The emptied buffer is kept rather than deleted: dropping it would let the next read rehydrate the
 * very history that was just cleared. Its write stream is closed, since the only caller is a config
 * deletion and the process will never write again.
 * @param {string} applicationId
 * @param {string} processId
 */
export function clear(applicationId, processId) {
  const key = bufferKey(applicationId, processId);
  const buffer = buffers.get(key);
  if (buffer) {
    buffer.entries.fill(undefined);
    buffer.writes = 0;
  }
  const sink = sinks.get(key);
  if (sink) enqueue(sink, () => endStream(sink)).catch(noop);
}

/** Flush and close every JSONL stream. Queued appends are written first. */
export async function closeAll() {
  const flushed = [...sinks.values()].map((sink) => enqueue(sink, () => endStream(sink)));
  await Promise.all(flushed.map((done) => done.catch(noop)));
}

/**
 * A cursor is either a real number or nothing: `Number('')` is 0, so an absent or blank `sinceSeq`
 * read as a number would look like the cursor of a client that had already seen the whole log and
 * would raise a spurious `dropped` on every fresh reader.
 */
const toCursor = (value) => {
  if (typeof value === 'string' && value.trim() === '') return null;
  if (value === null || value === undefined) return null;
  const seq = Number(value);
  return Number.isFinite(seq) ? seq : null;
};

function bufferFor(applicationId, processId) {
  const key = bufferKey(applicationId, processId);
  const existing = buffers.get(key);
  if (existing) return existing;

  const capacity = Math.max(1, Math.trunc(LOG_BUFFER_LINES));
  const buffer = { applicationId, processId, entries: new Array(capacity), writes: 0 };
  buffers.set(key, buffer);
  // First touch after a manager restart: the ring is empty, but the JSONL still holds the history.
  rehydrate(buffer);
  return buffer;
}

const evicted = (buffer) => buffer.writes > buffer.entries.length;

const store = (buffer, entry) => {
  buffer.entries[buffer.writes % buffer.entries.length] = entry;
  buffer.writes += 1;
};

/** The ring in seq order: the oldest live slot first, wrapping at the write head. */
function ascending(buffer) {
  const { entries, writes } = buffer;
  if (!evicted(buffer)) return entries.slice(0, writes);
  const head = writes % entries.length;
  return entries.slice(head).concat(entries.slice(0, head));
}

// ---------------------------------------------------------------------------------------------
// Cold-start rehydration — reads the tail of the JSONL once, when a buffer is first created.
// ---------------------------------------------------------------------------------------------

function rehydrate(buffer) {
  if (!LOG_PERSIST) return;
  const file = logFile(buffer.applicationId, buffer.processId);
  if (!file) return;
  for (const line of tailLines(file, buffer.entries.length)) {
    const entry = parseStored(line, buffer.processId);
    if (entry) store(buffer, entry);
  }
}

/** Old lines are renumbered: seq is a live cursor, and the previous run's numbering is gone. */
function parseStored(line, processId) {
  try {
    const { ts, stream, message } = JSON.parse(line);
    if (typeof message !== 'string') return null;
    return { seq: nextSeq++, ts: String(ts), stream: streamOf(stream), processId, message };
  } catch {
    return null;
  }
}

/**
 * Last `n` lines of a file, read backwards in chunks so a large log is never loaded whole.
 * Synchronous on purpose: it runs once per process, off the hot path, and keeps `read()` sync.
 * @param {string} file
 * @param {number} n
 */
function tailLines(file, n) {
  if (n <= 0) return []; // slice(-0) is slice(0) and would return the entire file
  let fd = null;
  try {
    fd = fs.openSync(file, 'r');
    const size = fs.fstatSync(fd).size;
    const floor = Math.max(0, size - TAIL_MAX_SCAN_BYTES);
    const chunks = [];
    let pos = size;
    let newlines = 0;
    while (pos > floor && newlines <= n) {
      const length = Math.min(TAIL_CHUNK_BYTES, pos - floor);
      pos -= length;
      const chunk = readFully(fd, pos, length);
      if (!chunk) return []; // short read: the file was truncated under us, so the tail is not ours
      chunks.unshift(chunk);
      newlines += countNewlines(chunk);
    }
    // Decode exactly once: a per-chunk toString() corrupts a multi-byte character on a boundary.
    const lines = Buffer.concat(chunks).toString('utf8').split('\n');
    if (pos > 0) lines.shift(); // the first line is the tail end of a line we did not read
    return lines.filter(Boolean).slice(-n);
  } catch {
    return []; // no file yet, or unreadable — cold start simply has no history
  } finally {
    if (fd !== null) fs.closeSync(fd);
  }
}

/**
 * `readSync` may return fewer bytes than asked for, which would leave a hole in the middle of the
 * concatenated tail. Fill the buffer, or report that the file no longer holds what we meant to
 * read.
 * @returns {Buffer|null}
 */
function readFully(fd, position, length) {
  const chunk = Buffer.allocUnsafe(length);
  let filled = 0;
  while (filled < length) {
    const bytesRead = fs.readSync(fd, chunk, filled, length - filled, position + filled);
    if (bytesRead <= 0) return null;
    filled += bytesRead;
  }
  return chunk;
}

function countNewlines(chunk) {
  let count = 0;
  for (let i = chunk.indexOf(0x0a); i !== -1; i = chunk.indexOf(0x0a, i + 1)) count += 1;
  return count;
}

// ---------------------------------------------------------------------------------------------
// JSONL persistence — one queue per process, so appends and rotation can never interleave.
// ---------------------------------------------------------------------------------------------

function persist(applicationId, processId, entry) {
  if (!LOG_PERSIST) return;
  const sink = sinkFor(applicationId, processId);
  if (!sink || sink.disabled) return;
  const { seq, ts, stream, message } = entry;
  enqueue(sink, () => writeLine(sink, `${JSON.stringify({ seq, ts, stream, message })}\n`))
    .catch((err) => disable(sink, err));
}

function sinkFor(applicationId, processId) {
  const key = bufferKey(applicationId, processId);
  const existing = sinks.get(key);
  if (existing) return existing;
  const file = logFile(applicationId, processId);
  if (!file) return null;
  const sink = { file, stream: null, bytes: 0, queue: Promise.resolve(), disabled: false };
  sinks.set(key, sink);
  return sink;
}

/** The `then(noop, noop)` tail is load-bearing: without it one failure poisons the whole queue. */
function enqueue(sink, task) {
  const run = sink.queue.then(task);
  sink.queue = run.then(noop, noop);
  return run;
}

async function writeLine(sink, line) {
  if (sink.disabled) return;
  const stream = sink.stream ?? (await openStream(sink));
  // Backpressure: a slow disk must not balloon the manager's memory with buffered lines.
  if (!stream.write(line)) await once(stream, 'drain');
  sink.bytes += Buffer.byteLength(line);
  if (sink.bytes >= LOG_FILE_MAX_BYTES) await rotate(sink);
}

async function openStream(sink) {
  await mkdir(path.dirname(sink.file), { recursive: true });
  sink.bytes = await stat(sink.file).then((s) => s.size, () => 0);
  const stream = fs.createWriteStream(sink.file, { flags: 'a' });
  // A stream with no 'error' handler turns a full disk into an uncaught exception. Clear only this
  // stream: a rotation may already have installed its successor by the time the failure lands.
  stream.on('error', (err) => {
    if (sink.stream === stream) sink.stream = null;
    stream.destroy();
    disable(sink, err);
  });
  sink.stream = stream;
  return stream;
}

/**
 * Rotation runs inside the write queue and always ends the stream before renaming: renaming out
 * from under an open fd keeps writing to the orphaned inode on POSIX and fails on Windows.
 * `end(cb)` flushes what is buffered; `close()`/`destroy()` does not.
 */
async function rotate(sink) {
  const stream = sink.stream;
  if (!stream) return; // the stream failed between the write and here; persistence is going down
  sink.stream = null;
  sink.bytes = 0;
  await finish(stream);
  const rotated = sink.file.replace(/\.jsonl$/, '.1.jsonl');
  await rm(rotated, { force: true }); // rename over an existing file fails on Windows
  await rename(sink.file, rotated);
}

async function endStream(sink) {
  const stream = sink.stream;
  if (!stream) return;
  sink.stream = null;
  await finish(stream);
}

/**
 * A stream that fails never emits 'finish', so waiting on `end(cb)` alone would hang the queue —
 * and with it shutdown. Settle on whichever of the flush, the failure or the close arrives.
 * @param {fs.WriteStream} stream
 */
function finish(stream) {
  if (stream.destroyed || stream.closed) return Promise.resolve();
  return new Promise((resolve) => {
    stream.once('close', resolve);
    stream.once('error', resolve);
    stream.end(resolve);
  });
}

function disable(sink, err) {
  sink.stream?.destroy(); // the fd is useless now; leaving it open leaks it for the whole session
  sink.stream = null;
  if (sink.disabled) return; // one message per process, however many writes are already queued
  sink.disabled = true;
  console.error(`[paddock] log persistence disabled for ${sink.file}: ${err.message}`);
}
